<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" tests="8" skipped="8" failures="0" errors="0" timestamp="2020-04-07T05:13:37" hostname="jaydeMacBook-Pro.local" time="0.004">
  <properties/>
  <testcase name="asyncMethodReturningFutureGetsRoutedAsynchronouslyAndReturnsAFuture" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.002">
    <skipped/>
  </testcase>
  <testcase name="exceptionHandlerCalled" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.001">
    <skipped/>
  </testcase>
  <testcase name="syncMethodGetsRoutedSynchronously" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="methodReturningFutureInAsyncClassGetsRoutedAsynchronouslyAndReturnsAFuture" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="qualifiedAsyncMethodsAreRoutedToCorrectExecutor" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="asyncMethodGetsRoutedAsynchronously" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="exceptionHandlerNeverThrowsUnexpectedException" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="voidMethodInAsyncClassGetsRoutedAsynchronously" classname="org.springframework.scheduling.aspectj.AnnotationAsyncExecutionAspectTests" time="0.001">
    <skipped/>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
